// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjlhbmfgqjrwpurcgaxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbGhibWZncWpyd3B1cmNnYXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjUxNTUsImV4cCI6MjA2NDc0MTE1NX0.9GtfKsZ2WEsRfTJWV-O1TQBXFGSe1Bk86x8uIp3Pmaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Expose URL and key for direct fetch calls when needed
export const supabaseConfig = {
  supabaseUrl: SUPABASE_URL,
  supabaseKey: SUPABASE_PUBLISHABLE_KEY
};

// Add to supabase object for convenience
(supabase as any).supabaseUrl = SUPABASE_URL;
(supabase as any).supabaseKey = SUPABASE_PUBLISHABLE_KEY;
